export const S = {
  container: { minHeight: "100vh", background: "#FAFAF9", position: "relative", overflow: "hidden", fontFamily: "'DM Sans', sans-serif" },
  bgOrb1: { position: "fixed", top: "-15%", right: "-10%", width: "500px", height: "500px", borderRadius: "50%", background: "radial-gradient(circle, rgba(251,191,36,0.08) 0%, transparent 70%)", animation: "float1 12s ease-in-out infinite", pointerEvents: "none" },
  bgOrb2: { position: "fixed", bottom: "-10%", left: "-5%", width: "400px", height: "400px", borderRadius: "50%", background: "radial-gradient(circle, rgba(99,102,241,0.06) 0%, transparent 70%)", animation: "float2 15s ease-in-out infinite", pointerEvents: "none" },
  bgOrb3: { position: "fixed", top: "50%", left: "50%", width: "600px", height: "600px", borderRadius: "50%", background: "radial-gradient(circle, rgba(16,185,129,0.04) 0%, transparent 70%)", transform: "translate(-50%,-50%)", pointerEvents: "none" },
  wrapper: { maxWidth: "880px", margin: "0 auto", padding: "48px 24px", position: "relative", zIndex: 1 },
  header: { textAlign: "center", marginBottom: "40px" },
  badge: { display: "inline-block", padding: "6px 16px", background: "#1a1a2e", color: "#FBBF24", fontSize: "10px", fontWeight: 700, letterSpacing: "2px", borderRadius: "100px", marginBottom: "20px" },
  title: { fontFamily: "'Instrument Serif', serif", fontSize: "clamp(36px,6vw,60px)", fontWeight: 400, color: "#1a1a2e", lineHeight: 1.1, marginBottom: "14px" },
  titleAccent: { fontStyle: "italic", background: "linear-gradient(135deg, #F59E0B, #D97706)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" },
  subtitle: { fontSize: "16px", color: "#6B7280", maxWidth: "440px", margin: "0 auto", lineHeight: 1.6 },
  card: { background: "#FFFFFF", borderRadius: "20px", padding: "28px", border: "1px solid #E5E7EB", boxShadow: "0 1px 3px rgba(0,0,0,0.04)", marginBottom: "16px" },
  cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "12px" },
  cardLabel: { fontSize: "14px", fontWeight: 600, color: "#1a1a2e" },
  ghostBtn: { padding: "6px 14px", background: "transparent", border: "1.5px solid #D1D5DB", borderRadius: "8px", fontSize: "12px", fontWeight: 600, color: "#6B7280", cursor: "pointer", fontFamily: "'DM Sans', sans-serif", transition: "all 0.2s" },
  textarea: { width: "100%", padding: "16px 20px", border: "1.5px solid #E5E7EB", borderRadius: "14px", fontSize: "15px", fontFamily: "'DM Sans', sans-serif", color: "#1a1a2e", background: "#FAFAF9", resize: "vertical", lineHeight: 1.7, transition: "all 0.2s" },
  toneBtn: { padding: "8px 14px", borderRadius: "10px", fontSize: "12px", fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans', sans-serif", transition: "all 0.2s" },
  error: { marginTop: "12px", padding: "10px 16px", background: "#FEF2F2", border: "1px solid #FECACA", borderRadius: "10px", color: "#DC2626", fontSize: "13px", fontWeight: 500 },
  generateBtn: { width: "100%", marginTop: "20px", padding: "16px 32px", background: "#1a1a2e", color: "#FBBF24", border: "none", borderRadius: "14px", fontSize: "15px", fontWeight: 700, fontFamily: "'DM Sans', sans-serif", cursor: "pointer", transition: "all 0.3s", letterSpacing: "0.5px" },
  spinner: { display: "inline-block", width: "18px", height: "18px", border: "2.5px solid rgba(251,191,36,0.3)", borderTopColor: "#FBBF24", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  pre: { fontFamily: "'DM Sans', sans-serif", fontSize: "14px", lineHeight: 1.8, color: "#374151", whiteSpace: "pre-wrap", wordBreak: "break-word", margin: 0, background: "#F9FAFB", padding: "20px", borderRadius: "12px", maxHeight: "380px", overflowY: "auto" },
};